spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.177:3306/wx?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

  spring:
    thymeleaf:
      prefix:
        classpath: /templates   # 访问template下的html文件需要配置模板，映射
      cache: false              # 开发时关闭缓存,不然没法看到实时页面

  mvc:
    view:
      prefix: /
      suffix: .html/.text
    static-path-pattern: /**

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl


#server:
#  port: 443
#  ssl:
#    key-store: classpath:8165766_zcsyuansheng.xyz.pfx
#    key-store-password: aucH052N
#    key-store-type: PKCS12
#  servlet:
#    encoding:
#      charset: UTF-8