spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wx?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: rootr
    password: gps@gps123

  mvc:
    view:
      prefix: /
      suffix: .html/.text
    static-path-pattern: /**

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl


server:
  port: 443
  ssl:
    key-store: classpath:5937354_www.zcsyuansheng.xyz.pfx
    key-store-password: L0J9X9pj
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8